const Discord = require("discord.js")
const db = require("quick.db")
const config = require("../config.json")
module.exports = {
    name: "stock", // Coloque o nome do comando do arquivo
    run: async(client, message, args) => {
        const embederro = new Discord.MessageEmbed()
        .setTitle(`Erro - Permissão`)
        .setDescription(`Você não tem permissão para isto!`)
        .setColor(config.cor)
        .setFooter(`${config.nomebot} - Todos os direitos reservados.`)
                if (!message.member.permissions.has("ADMINISTRATOR")) return message.channel.send({ embeds: [embederro] })
        const embed = new Discord.MessageEmbed()
        .setTitle(`✨ | ${config.nomebot} | Comandos do Bot`)
        .addField(`📌 | ${config.prefix}help`, `\`Exibe está mensagem\``)
        .addField(`📌 | ${config.prefix}add`, `\`Cria um produto para venda\``)
        .addField(`📌 | ${config.prefix}stock`, `\`Mostra todos os produtos que você tem a venda\``)
        .addField(`📌 | ${config.prefix}stockid \`ID\``, `\`Mostra o estoque do produto que você colocou o ID\``)
        .addField(`📌 | ${config.prefix}set \`ID\``, `\`Cria a mensagem de compra do produto\``)
        .addField(`📌 | ${config.prefix}gerenciar`, `\`gerenciar <id produto> , gerencia os produtos nome, preço e estoque do produto , veja os ids dos produto com o comando: ${config.prefix}stock\``)
        .addField(`📌 | ${config.prefix}limpar`, `\`Limpa as mensagens do canal\``)
        .addField(`📌 | ${config.prefix}estatisticas`, `\`Mostra as estatisticas de suas vendas\``)
        .addField(`📌 | ${config.prefix}perfil`, `\`Mostra o perfil de quem enviou o comando(liberado para todos os usuarios)\``)
        .addField(`📌 | ${config.prefix}rank`, `\`Mostra o rank de pessoas que mais compraram\``)
        .addField(`📌 | ${config.prefix}infobot`, `\`Mostra as informações do bot e o link dele\``)
        .addField(`📌 | ${config.prefix}manager`, `\`Mostra as informações de sua aplicação\``)
        .addField(`📌 | ${config.prefix}taxa`, `\`Muda a taxa de suas vendas pelo bot\``)
        .addField(`📌 | ${config.prefix}status`, `\`Utilize ${config.prefix}status <id da venda> para ver se a compra teve um problema ou foi aprovada\``)
        .addField(`📌 | ${config.prefix}del`, `\`Caso seu gerenciar não abra, use esse comando e delete algum produto\``)
        .addField(`📌 | ${config.prefix}anunciar`, `\`Envia uma mensagem do bot com say e embed por perguntas\``)
        .addField(`📌 | ${config.prefix}reembolso`, `\`reembolso + id da compra , reembolsa a venda automatico.\``)
        .addField(`📌 | ${config.prefix}setavatar`, `\`Muda a foto do bot para uma nova por link\``)
        .addField(`📌 | ${config.prefix}perm`, `\`Envia uma embed com botão , quem apertar nele tem permissão para utilizar os comandos do bot (cuidado).\``)
        .addField(`📌 | ${config.prefix}criarcupom`, `\`Cria um cupom para você utilizar no bot (use o comando para configurar cupons para modificar ele)\``)
        .addField(`📌 | ${config.prefix}configcupom`, `\`configcupom + nome do cupom para você modificar as coisas do cupom (valor minimo , porcentagem , quantidade , etc ).\``)
.setColor(config.cor)
.setImage("https://media.discordapp.net/attachments/995587007680106556/1014737663703650334/PicsArt_09-01-12.21.24.jpg")
message.channel.send({embeds: [embed]})
        
    }
}
